#ifndef NOSTOTALLETUSHISTORIADLL_GLOBAL_H
#define NOSTOTALLETUSHISTORIADLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NOSTOTALLETUSHISTORIADLL_LIBRARY)
#  define NOSTOTALLETUSHISTORIADLL_EXPORT Q_DECL_EXPORT
#else
#  define NOSTOTALLETUSHISTORIADLL_EXPORT Q_DECL_IMPORT
#endif

#endif // NOSTOTALLETUSHISTORIADLL_GLOBAL_H
